### ISSUE TITLE
V3 challenge listing model doesn't have isBanner flag

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/tc-elasticsearch-feeder-service#11]
For the new generation of marathon matches that we are creating from the direct app, there is an option if the match is banner or traditional. These values should be a part of the challenge data model, as this is required in the future changes for submission module. This is was part of original requirement document, we missed in the implementation. Please refer to the requirement document in the google doc.

> Whether the MM challenge is banner or traditional match (isBanner = ?)

**Comment by skyhit** [comment]
`there is an option if the match is banner or traditional`
@sushilshinde @ajefts where does this information stored currently?

**Comment by sushilshinde** [comment]
@skyhit this information is not store anywhere for old matches (before direct-MM update), but for new matches we will create from the direct  will always have this info. 

Old matches will have flag isLegacy=true

New matches will have match type

![topcoder direct](https://user-images.githubusercontent.com/683231/37597294-08db5304-2ba5-11e8-906b-ad3a71e6c625.png)

**Comment by skyhit** [comment]
@sushilshinde you mean for marathon match (round id), if it is associated with a challenge (properties), then it is a banner match, otherwise it is classic?

**Comment by skyhit** [comment]
@sushilshinde see https://github.com/appirio-tech/direct-app/pull/346/files, if so, I think the challenge properties already have this, so we just need to check the Marathon Match Type property, if it is missing or `Classic`, so `isLegacy = true`

if the value is `Banner`, so `isBanner = true`

**Comment by sushilshinde** [comment]
@skyhit 

Legacy matches mean all the matches that were created from non-direct UI

Banner and Traditional matches are different category

**Comment by skyhit** [comment]
@sushilshinde see this

![image](https://user-images.githubusercontent.com/58106/37824028-4f948206-2ec6-11e8-89ff-58b4ce255f10.png)

we should finalize this first

**Comment by sushilshinde** [comment]
@skyhit let's discuss on slack

**Comment by cwdcwd** [comment]
@skyhit How close are we to having this fixed?

**Comment by skyhit** [comment]
done
