### ISSUE TITLE
V3 challenge listing model doesn't have isLegacy flag

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/tc-elasticsearch-feeder-service#12]
For all legacy MM, there is no corresponding project ID so such challenges have to be flagged with `isLegacy = true`. This is was part of original requirement document, we missed in the implementation. 

> 3. b. Challenge is legacy MM or direct MM (isLegacy = ?)
> 4. 2 for legacy matches(already created from the Admin Tool) will read data from rounds tables and will 
>     not have project id, in that case, project id will be the round id. And #3.b will be isLegacy = true
>

**Comment by skyhit** [comment]
@sushilshinde index part population is completed, need to check with challenge service part, to get this info populated.
