### ISSUE TITLE
Need legacy data in challenge listing model

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/tc-elasticsearch-feeder-service#24]
Need these new attributes in Challenge listing ES index. All the legacy MMs should contain values. This is urgent.

contestId, componentId, roundId

**Comment by skyhit** [comment]
@sushilshinde  for legacy MM, the _id is the round id.
for contest id, component id, it needs to populate, but this is really changing the challenge model in ES.

**Comment by skyhit** [comment]
@sushilshinde so if you got a item in elasticsearch, whose track is Data Science, and whose subTrack is Marathon Match, the id field will be the round id, not challenge id.

if a item, whose track is Develop, and whose subTrack is Develop Marathon Match, we can get the round id from challenge properties.

**Comment by sushilshinde** [comment]
Yes, you are right. It will change ES model for now but we will change it back later. For other question please ping me slack @skyhit

**Comment by skyhit** [comment]
fixed.
