### ISSUE TITLE
ForumIds are wrong for past MMs

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/tc-elasticsearch-feeder-service#94]
https://www.topcoder.com/challenges/17323
http://api.topcoder.com/v4/challenges/17323

**Comment by skyhit** [comment]
@sushilshinde I see it is correct.

from https://community.topcoder.com/longcontest/stats/?module=ViewOverview&rd=17323, I can see the forum link is https://apps.topcoder.com/forums/?module=ThreadList&forumID=643602

and from api, the `forumId` field is 643602, and the `forumLink` is https://apps.topcoder.com/forums/?module=ThreadList&forumID=643602


for a past challenge, it is correct - https://api.topcoder.com/v4/challenges/17025 too

**Comment by sushilshinde** [comment]
@ajefts @skyhit this is a community app bug 

https://github.com/topcoder-platform/community-app/issues/1795
